baseURL = "/"
languageCode = "zh-cn"
title = "Nighthawk's nest"
theme = "github-style"
pygmentsCodeFences = true   # å¯åŠ¨ä»£ç é«˜äº®
pygmentsUseClasses = false
buildDrafts = false
PygmentsStyle = "tango"
enableEmoji = true  # æ”¯æŒ emoji

# åœ¨ md é‡Œé¢å¯ç”¨ HTML 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "ä½ çš„åå­—"
  description = "ä½ çš„æè¿°"
  github = "GitHub ID"
  email = "é‚®ç®±"
  url = "ä¸ªäººç½‘ç«™åœ°å€"
#   keywords = "blog, google analytics"
  # rss = true
  # userStatusEmoji = "ğŸ˜€"
  favicon = "/images/ava_c_trans.png" #æ ‡ç­¾é¡µçš„é‚£ä¸ªå°å›¾æ ‡
  avatar = "/images/ava_c.png"
  headerIcon = "/images/ava_c.png"
  location = "Shenzhen, China"
  enableGitalk = false
  # æ”¯æŒæœ¬åœ°æœç´¢ï¼Œè¿™é‡Œä¸ä¸‹é¢çš„ outputs
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

#   [params.gitalk]
#     clientID = ""
#     clientSecret = ""
#     repo = "å­˜æ”¾è¯„è®ºçš„ repo å"
#     owner = "ä½ çš„GitHub ID"
#     admin = "ä½ çš„GitHub ID"
#     id = "decodeURI(location.pathname)"
#     labels = "gitalk"
#     perPage = 15
#     pagerDirection = "last"
#     createIssueManually = false
#     distractionFreeMode = false


  [[params.links]]
    title = "bilibili"
    href = "https://space.bilibili.com/205319947"
    icon = "/images/bilibili.svg"

  [[params.links]]
    title = "QQ Group"
    icon = "/images/qq.svg"
    href = "https://qm.qq.com/q/cXb0hh1uC"

    [[params.links]]
    title = "ebird"
    href = "https://ebird.org/profile/MjQ3NDIyOQ/world"
    icon = "/images/ebirdicon.png"

lastmod = true
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

# [services]
#   [services.googleAnalytics]
#     ID = "UA-123456-789"


